### ISSUE TITLE
lastcontact oder updatedat in nodeliste aufnehmen

### ISSUE THREAD

**Issue by StilgarBF** [ffnord/ffmap-d3#105]
Hi,

könnte in die Knotenliste eine Information mit aufgenommen werden, wann der letzte Kontakt zum Knoten erfolgreich war.
- also wann er das letzte mal online war.

Im Moment gibt es die Info, dass ein Knoten offline ist - aber nicht wie lange schon.

Ich würde die Information gern in der Freifunk-Karte nutzen.

**Comment by tcatm** [comment]
Das gibt's sogar schon im dev-Branch von ffmap-backend (https://github.com/ffnord/ffmap-backend/tree/dev). Allerdings wird das noch nirgends eingesetzt, weil das Frontend noch nicht dafür angepasst wurde.

**Comment by StilgarBF** [comment]
wäre es denkbar, dass auszuspielen auch ohne, dass es unmittelbar im ffmap-frontend gezeigt wird?

Ich will in www.freifunk-karte.de gern Zugangspunkte ausblenden, die schon lange offline sind. Dort ist das sicher sinnvoll, da ich den Hauptzweck der Karte darin sehe, nutzbare Zugangspunkte zu suchen.

Bin mir durchaus im Klaren darüber, dass es vermutlich sehr sehr lange dauern wird, bis alle Communities ihre ffmap aktualisieren.

**Comment by tcatm** [comment]
Das aktuelle frontend kann mit den neuen Daten leider garnichts anfangen, darum könnte es noch ein bisschen dauern bis das neue backend eingesetzt werden kann.

**Comment by tcatm** [comment]
Ich hab das Backend mal experimentell für Lübeck deployed:

https://map.luebeck.freifunk.net/data/nodes.json
https://map.luebeck.freifunk.net/data/graph.json

**Comment by StilgarBF** [comment]
Wäre es denn möglich dieses Feld auch in die aktuelle nodes.json aufzunehmen? als kleine Änderung ohne alles auf die neue Version zu heben?

Ich verarbeite/unterscheide im Parser der Karte ohnehin die alte und neue Struktur.

**Comment by tcatm** [comment]
Das neue Backend hat seit ein paar Tagen das alte ersetzt. Die Daten stehen jetzt in vielen Communities zu Verfügung. Für weitere Fragen zum Datenformat ist https://github.com/ffnord/ffmap-backend dann das richtige Repo. Das hier ist ja nur ein Frontend.
