### ISSUE TITLE
Map, Graph and List does not work with Internet Explorer 

### ISSUE THREAD

**Issue by flammy** [ffnord/ffmap-d3#106]
The Map, Graph and List does not work with Internet Explorer.

I have testet Internet Explorer 11.

Internet Explorer throws an error "Object does not support this action" to "throw e"  on this line:

Bacon.js ca. line 1497

    catch (_error) {
        e = _error;
        this.pushing = false;
        this.queue = [];
        throw e;
      }

**Comment by tcatm** [comment]
Try Chrome, Firefox or Opera. Internet Explorer often lacks features found in other browsers.
