### ISSUE TITLE
Zukunft dieses Projekts

### ISSUE THREAD

**Issue by tcatm** [ffnord/ffmap-d3#113]
Ich habe in letzten Wochen ein [neues Frontend](https://github.com/tcatm/meshviewer) für ffmap-backend gebaut, das nun schon viele Funktionen von ffmap-d3 beherrscht und einige zusätzliche Features hat. Insbesondere zeigt es mehr Daten der Knoten an und funktioniert auf mobilen Geräten.
Auch die Codebasis ist aufgeräumter und Erweiterungen leichter möglich.

Daher würde ich das Projekt ffmap-d3 gerne beende und vielleicht sogar das Repository löschen (der Code ist wirklich nicht schön). Hat da jemand etwas gegen?

**Comment by kokel** [comment]
Erstmal vielen Dank für das neue Karten Frontend, gefällt mir sehr gut!

Warum willst du das alte Frontend denn löschen? Ein Umbenennen und Hinweis darauf, dass es nicht weiterentwickelt wird würde doch zunächst ausreichen.

**Comment by tcatm** [comment]
Ich find den Code grausig und es gibt sowieso schon viel zu viele Forks...

**Comment by pixelistik** [comment]
So lange noch Instanzen dieser Map irgendwo in Betrieb sind, fände ich es hilfreich, wenn das Repository online bleibt. Gerade angesichts der diversen Forks würde es nicht gerade übersichtlicher werden, wenn das „upstream”-Projekt nicht mehr vorhanden ist und Links ins Leere laufen.

**Comment by rubo77** [comment]
Ich denke auch, dieses Upstream Projekt sollte als Projekt in github erhalten bleiben aus Gründen der konsistenz mit den ganzen forks.

Sinnvoll wäre hier einen letzten commit, der alle Dateien löscht und nur noch ein README enthält, das auf das nachfolge projekt verweist und eine Bitte auch alle forks auf den Nachfolger upzudaten.

Das neue Projekt sieht super aus!
Freu mich schon drauf ;)

**Comment by tcatm** [comment]
Version 1 von [meshviewer](https://github.com/tcatm/meshviewer) ist nun fertig und dieses Projekt damit deprecated.
