### ISSUE TITLE
freifunkkarte verbessern: Legende+uplinks

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffmap-d3#34]
was heissen wigentlich die zahlen auf der freifunkkarte hinter den rountenamen in klammern?
Irgendwie mal ne legende wäre gut.

Und wenn man auf der karte auch sehen würde, welche router einen uplink haben

**Comment by tcatm** [comment]
Die Zahlen in den Klammern sind schon länger nicht mehr vorhanden.
