### ISSUE TITLE
Voreingestellte Position

### ISSUE THREAD

**Issue by 4ndr3** [ffnord/ffmap-d3#70]
Feature request: Momentan errechnet die Karte beim Laden anhand der vorhandenen Knotenkoordinaten die Position des Ausschnittes auf der Weltkarte sowie die Vergrößerung.
Das führt dazu, dass man bei jeder Betrachtung sehr stark vergrößern und die Karte an die richtige Position bewegen muss, wenn Knoten weit ausserhalb des Stadtgebietes eingetragen werden (was durchaus Gang und Gebe ist).
Es wäre toll, wenn man alternativ Koordinaten und ein Vergrößerungsstufe fest voreinstellen könnte. Prinzipiell müssten dazu wahrscheinlich nur an der Stelle im Code wo heute diese beiden Werte berechnet werden Konstanten eingetragen werden.

**Comment by lost-tty** [comment]
Der neue meshviewer setzt die Position nun auf den Median aller Knoten und zoomt auf die Standardabweichung. Der Zoomfaktor ist zudem in der config einstellbar.
